language: python

python:
  - 3.6
  - 3.7
  - 3.8

install: 
  - pip install -r requirements.txt

script:
  - python -m pytest -v

deploy:
  provider: heroku
  api_key:
    secure: ac817b7e-a017-4b72-a358-fd23e1b8f68b
  app: cortts-accounts-backend
  on:
    repo: preciousidam/cortts-accounts-backend